module.exports = {
  source: ["package.json", "packages/*/package.json"],
  indent: "  ",
  semverGroups: [
    {
      range: "",
      dependencies: ["@voltagent/**"],
      packages: ["**"],
    },
  ],
  sortAz: [
    "dependencies",
    "devDependencies",
    "peerDependencies",
    "optionalDependencies",
    "resolutions",
  ],
  sortFirst: [
    "name",
    "version",
    "private",
    "description",
    "license",
    "author",
    "repository",
    "homepage",
    "bugs",
    "main",
    "module",
    "types",
    "exports",
    "files",
    "bin",
    "scripts",
    "dependencies",
    "peerDependencies",
    "devDependencies",
    "optionalDependencies",
    "resolutions",
  ],
  versionGroups: [
    {
      label: "Use workspace protocol when developing local packages",
      dependencies: ["@voltagent/**"],
      dependencyTypes: ["dependencies", "peerDependencies"],
      packages: ["**"],
      policy: "workspace",
    },
  ],
};
